services:
  fastapi:
    container_name: gemma-fastapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.FastAPI
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8000:8000"
    networks:
      - gemma-net

  streamlit:
    container_name: gemma-streamlit
    env_file:
      - .env
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.Streamlit
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - gemma-net

networks:
  gemma-net:
    driver: bridge
