FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV PYTHONPATH=/app

# CMD ["streamlit", "run", "src/main/gemma_system/app/main.py", "--server.port=8000", "--server.address=0.0.0.0"]
CMD ["streamlit", "run", "src/main/gemma_system/app/main.py", "--server.port=8000", "--server.address=0.0.0.0"]